import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import styles from "./page.module.css";
import ImageLogo from './assets/images/Logo-Dafo-dobro-tamanho.png'
import Image from "next/image";

import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let value = true
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ToastContainer />
        <header className={styles.header}>
          <Image
            className={styles.logo}
            src={ImageLogo}
            alt="Next.js logo"
            priority
          />
          <h1 className={styles.text}>Pesagem das Ampolas do sistema SCI</h1>
        </header>

        {children}


      </body>
    </html>
  );
}
